'use client';

import { FormData } from './FormData';

interface PresetTemplatesProps {
  onApplyTemplate: (template: Partial<FormData>, templateName: string) => void;
}

export default function PresetTemplates({
  onApplyTemplate,
}: PresetTemplatesProps) {
  const templates = [
    {
      name: 'IKEA Prompt',
      icon: '🏠',
      description:
        'Cinematic shot of a sunlit Scandinavian bedroom with IKEA furniture assembly',
      template: {
        subject:
          'sealed IKEA box trembles, opens, and flat pack furniture assembles rapidly into a serene, styled room highlighted by a yellow IKEA throw on the bed',
        style: 'cinematic',
        setting: 'Scandinavian bedroom',
        cameraMovement: 'fixed wide angle',
        videoStyle: 'cinematic',
        lighting: 'natural warm with cool accents',
        pov: 'wide shot',
        composition: 'rule of thirds',
        vibe: 'serene',
        mood: 'calm',
        atmosphere: 'peaceful',
        weather: 'sunny',
        timeOfDay: 'daylight',
        season: 'spring',
        windSpeed: 'calm',
        visibility: 'clear',
        sense: 'visual',
        colors: 'warm and cool tones',
        textures: 'smooth',
        materials: 'wood and fabric',
        temperature: 'warm',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '30 seconds',
        movementSpeed: 'rapid',
        movementDirection: 'precise',
        lightIntensity: 'natural',
        lightDirection: 'sunlit',
        lightColor: 'warm with cool accents',
        povDistance: 'wide',
        povLensType: 'wide angle',
        compositionBalance: 'modern',
        compositionDepth: 'medium',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'still',
        emotions: 'satisfaction',
        actions: 'furniture assembly',
        actionSpeed: 'fast motion',
        energyLevel: 'precise',
        transition: 'smooth',
        details: 'IKEA logo visible, yellow throw on bed, modern space',
        additionalDetails: 'no text, fast assembly, Scandinavian design',
        model: 'runway',
      } as Partial<FormData>,
      color: '#ff9a8b',
    },
    {
      name: 'Amazon Gamer Room',
      icon: '🎮',
      description:
        'Cinematic Amazon box assembly creating a complete gamer room setup',
      template: {
        subject:
          'sealed Amazon box trembles, opens, and furniture pieces fly out assembling into a complete gamer room with bed, PC setup, and gaming accessories',
        style: 'cinematic',
        setting:
          'large sunlit Scandinavian room with white walls and light wood floors',
        cameraMovement: 'fixed wide angle',
        videoStyle: 'cinematic',
        lighting: 'natural daylight',
        pov: 'wide shot',
        composition: 'rule of thirds',
        vibe: 'dynamic',
        mood: 'excited',
        atmosphere: 'energetic',
        weather: 'sunny',
        timeOfDay: 'daylight',
        season: 'spring',
        windSpeed: 'calm',
        visibility: 'clear',
        sense: 'visual',
        colors: 'blue and dark tones',
        textures: 'smooth',
        materials: 'metal and fabric',
        temperature: 'warm',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '8 seconds',
        movementSpeed: 'hyper-lapse',
        movementDirection: 'flying assembly',
        lightIntensity: 'natural',
        lightDirection: 'sunlit',
        lightColor: 'natural',
        povDistance: 'wide',
        povLensType: 'wide angle',
        compositionBalance: 'asymmetrical',
        compositionDepth: 'deep',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'chaotic then still',
        emotions: 'excitement',
        actions: 'furniture assembly and flying pieces',
        actionSpeed: 'hyper-lapse speed',
        energyLevel: 'high energy',
        transition: 'smooth',
        details:
          'Amazon logo visible, dark blue duvet, blue throw blanket, metal table, neon lamps, gamer PC, monitor, keyboard, headsets',
        additionalDetails:
          'no people, no text overlays, no distracting music, ASMR sounds',
        model: 'runway',
      } as Partial<FormData>,
      color: '#ff6b35',
    },
    {
      name: 'Chewy Pet Supplies',
      icon: '🐕',
      description:
        'Cinematic Chewy box explosion creating a complete pet setup with happy dog',
      template: {
        subject:
          'sealed Chewy box trembles, explodes open in one burst, and pet supplies rapidly assemble into place with food bowls, dog bed, toys, and a dog runs in and flops into the bed',
        style: 'cinematic',
        setting: 'modern kitchen with hardwood floors',
        cameraMovement: 'fixed wide angle',
        videoStyle: 'cinematic',
        lighting: 'natural warm with soft shadows',
        pov: 'wide shot',
        composition: 'rule of thirds',
        vibe: 'joyful',
        mood: 'happy',
        atmosphere: 'warm',
        weather: 'sunny',
        timeOfDay: 'daylight',
        season: 'spring',
        windSpeed: 'calm',
        visibility: 'clear',
        sense: 'visual',
        colors: 'warm tones',
        textures: 'smooth',
        materials: 'fabric and plastic',
        temperature: 'warm',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '10 seconds',
        movementSpeed: 'rapid explosion',
        movementDirection: 'flying assembly',
        lightIntensity: 'natural',
        lightDirection: 'sunlit',
        lightColor: 'warm',
        povDistance: 'wide',
        povLensType: 'wide angle',
        compositionBalance: 'asymmetrical',
        compositionDepth: 'medium',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'explosive then calm',
        emotions: 'joy',
        actions: 'box explosion and pet supplies assembly',
        actionSpeed: 'rapid assembly',
        energyLevel: 'high energy',
        transition: 'smooth',
        details:
          'Chewy logo visible, dog food and water bowls, dog bed, dog toys (rope, ball, bone), bag of dog food, wall hook with leash, golden retriever dog',
        additionalDetails:
          'no text, fast assembly, pet supplies, dog enters and settles happily',
        model: 'runway',
      } as Partial<FormData>,
      color: '#4ecdc4',
    },
    {
      name: 'Corona Beach Rave',
      icon: '🍺',
      description:
        'Cinematic bottle transformation creating a magical beach rave from a Corona bottle',
      template: {
        subject:
          'cold dewy Corona bottle hums and vibrates, cap pops, and entire beach rave environment unfolds from inside with palm trees, lights, speakers, DJ booth, and crowd materializing',
        style: 'cinematic magical realism',
        setting: 'quiet beach transforms into high-energy beach rave',
        cameraMovement:
          'starts ultra close, zooms out and cranes overhead as world expands',
        videoStyle: 'cinematic',
        lighting: 'sunset turning to neon golden hour into party glow',
        pov: 'close up to wide shot',
        composition: 'rule of thirds',
        vibe: 'magical',
        mood: 'energetic',
        atmosphere: 'transformative',
        weather: 'sunny to night',
        timeOfDay: 'sunset to night',
        season: 'summer',
        windSpeed: 'calm to breezy',
        visibility: 'clear',
        sense: 'visual',
        colors: 'golden hour to neon',
        textures: 'smooth',
        materials: 'glass and sand',
        temperature: 'warm',
        humidity: 'humid',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '15 seconds',
        movementSpeed: 'rapid time-lapse',
        movementDirection: 'explosive expansion',
        lightIntensity: 'changing from natural to neon',
        lightDirection: 'sunset to party lights',
        lightColor: 'golden to neon',
        povDistance: 'close to wide',
        povLensType: 'variable',
        compositionBalance: 'dynamic',
        compositionDepth: 'deep',
        atmosphereDensity: 'thin to thick',
        atmosphereMovement: 'explosive transformation',
        emotions: 'excitement',
        actions: 'bottle transformation and rave assembly',
        actionSpeed: 'rapid time-lapse',
        energyLevel: 'explosive',
        transition: 'magical',
        details:
          'Corona bottle with label visible and condensation dripping, pop-top cap in slow motion, exploding citrus slice, sand morphing into dance floor, palm trees rising, neon lights snapping on, DJ booth building itself, crowd materializing mid-dance, fire pit lighting, surfboards as signage',
        additionalDetails:
          'no text, bottle transforms, rave build, sunset to night, magical realism',
        model: 'runway',
      } as Partial<FormData>,
      color: '#f7dc6f',
    },
    {
      name: 'Jeep Basecamp',
      icon: '🚙',
      description:
        'Epic cinematic reveal of a Jeep Wrangler Rubicon from a mechanical expedition crate in remote wilderness',
      template: {
        subject:
          'rugged mechanical expedition crate splits open with panels unfolding to reveal a fully-equipped Jeep Wrangler Rubicon at the center of an adventure-ready basecamp',
        style: 'cinematic gritty realistic epic',
        setting: 'Moab desert canyon at sunset',
        cameraMovement:
          'medium wide shot steady with slow push-in as vehicle is revealed',
        videoStyle: 'cinematic',
        lighting:
          'dramatic golden hour with long shadows lens flare warm functional light from camp gear',
        pov: 'medium wide shot',
        composition: 'rule of thirds',
        vibe: 'epic',
        mood: 'adventurous',
        atmosphere: 'rugged',
        weather: 'clear',
        timeOfDay: 'sunset',
        season: 'autumn',
        windSpeed: 'gentle',
        visibility: 'clear with dust',
        sense: 'visual',
        colors: 'golden hour warm',
        textures: 'rough',
        materials: 'metal and fabric',
        temperature: 'warm',
        humidity: 'dry',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '12 seconds',
        movementSpeed: 'slow mechanical',
        movementDirection: 'unfolding outward',
        lightIntensity: 'dramatic',
        lightDirection: 'golden hour',
        lightColor: 'warm',
        povDistance: 'medium',
        povLensType: 'normal',
        compositionBalance: 'heroic',
        compositionDepth: 'deep',
        atmosphereDensity: 'thin with dust',
        atmosphereMovement: 'gentle swirls',
        emotions: 'excitement',
        actions: 'mechanical crate unfolding',
        actionSpeed: 'slow mechanical',
        energyLevel: 'steady',
        transition: 'mechanical',
        details:
          'Jeep Wrangler Rubicon dirty mud-splattered, mechanical unfolding crate with Jeep logo, rooftop tent already deployed, glowing LED camp lights, solar panels, durable camping chairs, dust and grit in the air',
        additionalDetails:
          'no text, 4k hyperrealistic, adventure off-road basecamp rugged golden hour cinematic no people',
        model: 'runway',
      } as Partial<FormData>,
      color: '#8b4513',
    },
    {
      name: 'LEGO Porsche',
      icon: '🏎️',
      description:
        'Photorealistic LEGO Porsche 911 assembly from box to detailed model on kitchen counter',
      template: {
        subject:
          'sealed box of LEGO Porsche 911 Turbo and 911 Targa trembles, bursts open, and hundreds of glossy white black and orange LEGO pieces fly into the air and rapidly assemble into a sleek Porsche 911 model with detailed headlights curved fenders and opening trunk',
        style: 'photorealistic cinematic',
        setting:
          'modern kitchen with marble countertops minimal appliances and wooden bar stools',
        cameraMovement:
          'smooth dolly shot transitioning from close-up of box to wide shot of car assembling',
        videoStyle: 'cinematic',
        lighting: 'warm sunset glow with soft ambient shadows',
        pov: 'close-up to wide shot',
        composition: 'rule of thirds',
        vibe: 'precise',
        mood: 'satisfying',
        atmosphere: 'warm',
        weather: 'clear',
        timeOfDay: 'sunset',
        season: 'autumn',
        windSpeed: 'calm',
        visibility: 'clear',
        sense: 'visual',
        colors: 'white black and orange',
        textures: 'smooth',
        materials: 'plastic and marble',
        temperature: 'warm',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '10 seconds',
        movementSpeed: 'rapid assembly',
        movementDirection: 'flying and locking',
        lightIntensity: 'warm',
        lightDirection: 'sunset',
        lightColor: 'warm',
        povDistance: 'close to wide',
        povLensType: 'variable',
        compositionBalance: 'dynamic',
        compositionDepth: 'medium',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'flying pieces',
        emotions: 'satisfaction',
        actions: 'LEGO assembly and car building',
        actionSpeed: 'rapid assembly',
        energyLevel: 'precise',
        transition: 'smooth',
        details:
          'LEGO Porsche 911 Turbo and Targa box with Porsche logo visible, white black and orange LEGO pieces, sleek 911 body with headlights and taillights, detailed interior with steering wheel and dashboard, removable roof panel for Targa mode, LEGO driver minifigure in racing outfit, tiny tools and tire set on countertop',
        additionalDetails:
          'no text, fast assembly, photorealistic, sunset lighting, detailed car model, headlights flicker on, roof panel clicks into position',
        model: 'runway',
      } as Partial<FormData>,
      color: '#ff6b6b',
    },
    {
      name: 'Louis Vuitton Handbag Reveal',
      icon: '👜',
      description:
        'Luxurious cinematic transformation of LV logo into golden threads forming an elegant handbag',
      template: {
        subject:
          'golden monogram LV logo shimmers midair, disassembles into thousands of tiny gold threads flowing downward like liquid embroidery, weaving into detailed silhouette of Louis Vuitton handbag with glowing leather and gold zipper opening on its own',
        style: 'cinematic luxurious elegant',
        setting: 'black velvet tabletop with soft shadows and refined texture',
        cameraMovement: 'fixed wide angle',
        videoStyle: 'cinematic',
        lighting:
          'moody spotlight with warm golden highlights and gentle falloff',
        pov: 'wide shot',
        composition: 'rule of thirds',
        vibe: 'luxurious',
        mood: 'elegant',
        atmosphere: 'refined',
        weather: 'indoor',
        timeOfDay: 'evening',
        season: 'autumn',
        windSpeed: 'still',
        visibility: 'clear',
        sense: 'visual',
        colors: 'golden and black',
        textures: 'velvet and leather',
        materials: 'gold thread and leather',
        temperature: 'warm',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '15 seconds',
        movementSpeed: 'gentle flowing',
        movementDirection: 'downward weaving',
        lightIntensity: 'moody',
        lightDirection: 'spotlight',
        lightColor: 'warm golden',
        povDistance: 'wide',
        povLensType: 'wide angle',
        compositionBalance: 'centered',
        compositionDepth: 'shallow',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'gentle flow',
        emotions: 'awe',
        actions: 'logo transformation and thread weaving',
        actionSpeed: 'gentle flowing',
        energyLevel: 'elegant',
        transition: 'smooth',
        details:
          'gold LV monogram logo, golden embroidery threads, Louis Vuitton handbag silhouette, glowing leather texture, gold zipper movement, interior light reveal, monogram pattern subtly embossed',
        additionalDetails:
          'no text, luxury fashion, handbag reveal, embroidery transformation, elegance, cinematic branding, subtle cinematic string swell with harp accents, gentle thread weaving sounds leather flexing zipper slide',
        model: 'runway',
      } as Partial<FormData>,
      color: '#d4af37',
    },
    {
      name: 'Nike Ad',
      icon: '👟',
      description:
        'Hyper-stylized Nike Air Jordan transformation with character lip-sync on urban basketball court',
      template: {
        subject:
          'closed Nike shoebox levitates spins and explodes into vortex of sneaker parts as pair of glowing Air Jordans assembles mid-air with character stepping through smoke lip-syncing directly to camera as shoes lock onto their feet with kinetic blast',
        style: 'stylized cinematic with light surreal VFX',
        setting: 'dark misty urban basketball court at night',
        cameraMovement:
          'dynamic Steadicam and crane combo with slow crane-down into rotating dolly move then sudden handheld push-in during lip sync',
        videoStyle: 'cinematic',
        lighting:
          'high-contrast urban night lighting with overhead flickering halogen bounce from wet pavement rim lights from behind mist',
        pov: 'wide shot to close-up',
        composition: 'rule of thirds',
        vibe: 'powerful',
        mood: 'confident',
        atmosphere: 'urban night',
        weather: 'misty',
        timeOfDay: 'night',
        season: 'autumn',
        windSpeed: 'still',
        visibility: 'misty',
        sense: 'visual',
        colors: 'urban night tones',
        textures: 'wet pavement',
        materials: 'sneaker parts and techwear',
        temperature: 'cool',
        humidity: 'humid',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '12 seconds',
        movementSpeed: 'slow motion to fast',
        movementDirection: 'orbital assembly',
        lightIntensity: 'high contrast',
        lightDirection: 'overhead and rim',
        lightColor: 'urban night',
        povDistance: 'wide to close',
        povLensType: '28mm wide-angle',
        compositionBalance: 'dynamic',
        compositionDepth: 'deep',
        atmosphereDensity: 'misty',
        atmosphereMovement: 'volumetric fog',
        emotions: 'confidence',
        actions: 'shoebox explosion and shoe assembly',
        actionSpeed: 'slow motion to kinetic',
        energyLevel: 'powerful',
        transition: 'kinetic blast',
        details:
          'chain-link fencing backlit by headlights, wet pavement with puddle reflections, floating Nike shoebox with visible swoosh, slowly rising ambient smoke, young adult athletic build platinum buzzcut black techwear hoodie, Nike Air Jordan shoes with glow FX, shockwave ripple on impact',
        additionalDetails:
          'optional logo pulse at end only, product transformation, stylized VFX, lip sync, basketball court, power statement, cinematic advertising, shockwave impact, trap beat, hard-hitting trap beat with glitched snares and deep sub-bass swell during climax, voiceover line: "This ain\'t style. This is power."',
        model: 'runway',
      } as Partial<FormData>,
      color: '#ff4757',
    },
    {
      name: 'NYC Skyline',
      icon: '🏙️',
      description:
        'Cinematic NYC city assembly from sealed steel container creating iconic Manhattan skyline',
      template: {
        subject:
          'sealed steel shipping container stamped with NYC in bold letters trembles and bursts open as city elements rocket out and lock into place with steel beams rising glass facades snapping on bridges spanning into view and yellow taxis lining up automatically',
        style: 'cinematic photorealistic 4K',
        setting:
          'vast empty urban plaza at dawn with concrete pavement stretching into the mist',
        cameraMovement:
          'single fixed wide-angle shot holding position for entire duration',
        videoStyle: 'cinematic',
        lighting: 'dawn light with morning glow',
        pov: 'wide shot',
        composition: 'rule of thirds',
        vibe: 'urban',
        mood: 'awakening',
        atmosphere: 'misty dawn',
        weather: 'misty',
        timeOfDay: 'dawn',
        season: 'spring',
        windSpeed: 'calm',
        visibility: 'misty',
        sense: 'visual',
        colors: 'dawn tones',
        textures: 'concrete and steel',
        materials: 'steel glass and concrete',
        temperature: 'cool',
        humidity: 'humid',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '8 seconds',
        movementSpeed: 'hyper-lapse',
        movementDirection: 'rocketing assembly',
        lightIntensity: 'dawn',
        lightDirection: 'morning',
        lightColor: 'dawn',
        povDistance: 'wide',
        povLensType: 'wide angle',
        compositionBalance: 'urban',
        compositionDepth: 'deep',
        atmosphereDensity: 'misty',
        atmosphereMovement: 'swirling fog',
        emotions: 'awe',
        actions: 'city assembly and building construction',
        actionSpeed: 'hyper-lapse speed',
        energyLevel: 'dynamic',
        transition: 'smooth',
        details:
          'iconic Manhattan skyscrapers Empire State Building Chrysler Building, Brooklyn Bridge arching into frame, yellow taxi cabs lined up along street, hydrant and classic black street lamps, subway entrance staircase with MTA sign, Statue of Liberty torch and crown silhouette, Central Park trees emerging in background, water towers perched on rooftop structures, billboard frames and neon signs, sidewalk café tables and chairs full of people',
        additionalDetails:
          'no text overlays, no overt graphics, rapid sequence of ASMR city-building sounds metal clanks glass sliding cables snapping engines revving softly, soft engine cut-off chug then distant hum of awakening city traffic fading into serene dawn silence',
        model: 'runway',
      } as Partial<FormData>,
      color: '#74b9ff',
    },
    {
      name: 'Rimowa Suitcase',
      icon: '💼',
      description:
        'Editorial cinematic transformation of transparent suitcase into solid yellow Rimowa with mist effect',
      template: {
        subject:
          'upright transparent suitcase in plain white cyclorama studio with burst of yellow mist filling it as it spins rapidly transforming mid-spin into solid yellow hard-shell suitcase with chrome latches and telescopic handle',
        style: 'editorial cinematic',
        setting:
          'plain infinite white cyclorama with no texture no visible lights seamless floor-to-wall transition',
        cameraMovement:
          'precision dolly-in from 2.5m to 1.5m over 5 seconds then static hero shot',
        videoStyle: 'cinematic',
        lighting:
          'clean soft and even with no visible light sources or reflections lighting wraps naturally with minimal shadowing',
        pov: 'medium shot',
        composition: 'centered',
        vibe: 'clean',
        mood: 'precise',
        atmosphere: 'minimalist',
        weather: 'indoor',
        timeOfDay: 'daylight',
        season: 'all seasons',
        windSpeed: 'still',
        visibility: 'clear',
        sense: 'visual',
        colors: 'white and yellow',
        textures: 'smooth',
        materials: 'plastic and chrome',
        temperature: 'neutral',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '7 seconds',
        movementSpeed: 'rapid spin to static',
        movementDirection: 'vertical spin',
        lightIntensity: 'soft',
        lightDirection: 'wrapped',
        lightColor: 'clean white',
        povDistance: 'medium to close',
        povLensType: 'normal',
        compositionBalance: 'centered',
        compositionDepth: 'shallow',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'volumetric mist',
        emotions: 'satisfaction',
        actions: 'suitcase transformation and spin',
        actionSpeed: 'violent mist fill then clean halt',
        energyLevel: 'precise',
        transition: 'smooth',
        details:
          'transparent upright suitcase, volumetric yellow mist, solid yellow hard-shell suitcase with ribbed structure, chrome latches and telescopic handle, soft reflective white floor, faint lingering mist at base',
        additionalDetails:
          'no text, no humans, 4K, minimalist, editorial, product transformation, white cyclorama, clean studio, yellow mist, mist dissipates fade to white',
        model: 'runway',
      } as Partial<FormData>,
      color: '#fdcb6e',
    },
    {
      name: 'StrideX Sneaker Boutique',
      icon: '👟',
      description:
        'High-energy urban sneaker boutique with neon-accented self-lacing sneakers and holographic treadmill',
      template: {
        subject:
          'sealed StrideX shoe box rattles shoots open and neon-accented sneakers hover self-lacing mid-air sprint on treadmill of light and freeze in hero pose',
        style: 'high-energy commercial',
        setting: 'industrial retail space with concrete floor',
        cameraMovement: 'handheld whip-pan',
        videoStyle: 'cinematic',
        lighting: 'dynamic neon blues and magentas',
        pov: 'dynamic',
        composition: 'rule of thirds',
        vibe: 'energetic',
        mood: 'dynamic',
        atmosphere: 'urban night',
        weather: 'indoor',
        timeOfDay: 'night',
        season: 'all seasons',
        windSpeed: 'still',
        visibility: 'clear',
        sense: 'visual',
        colors: 'neon blues and magentas',
        textures: 'concrete',
        materials: 'sneaker materials and neon',
        temperature: 'cool',
        humidity: 'moderate',
        aspectRatio: '9:16',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '8 seconds',
        movementSpeed: 'explosive to freeze',
        movementDirection: 'whip-pan',
        lightIntensity: 'dynamic',
        lightDirection: 'neon',
        lightColor: 'blues and magentas',
        povDistance: 'variable',
        povLensType: 'wide angle',
        compositionBalance: 'dynamic',
        compositionDepth: 'medium',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'neon glow',
        emotions: 'excitement',
        actions: 'box explosion and sneaker sprint',
        actionSpeed: 'explosive then freeze',
        energyLevel: 'high energy',
        transition: 'sharp freeze',
        details:
          'StrideX box with logo glowing, self-lacing sneakers, holographic treadmill, LED floor grid, sneakers land on pedestal under spotlight',
        additionalDetails:
          'no text, sneakers, neon, motion freeze, high-energy commercial, urban sneaker boutique at night',
        model: 'runway',
      } as Partial<FormData>,
      color: '#a29bfe',
    },
    {
      name: 'Tennis Spin',
      icon: '🎾',
      description:
        'Hyper-real macro tennis ball revealing surreal spherical interior with miniature clay court and tennis player',
      template: {
        subject:
          'hyper-real macro tennis ball slowly cracks open like shell to reveal surreal spherical interior with miniature curved clay court embedded within felt-lined shell and female tennis player stands centered in middle third',
        style: 'editorial realism',
        setting:
          'interior of spherical tennis ball with warped clay court and surreal sportscape',
        cameraMovement:
          'macro static to pivot and dolly-in to lateral tracking to follow spinning ball',
        videoStyle: 'cinematic',
        lighting:
          'soft top-down editorial lighting with curved tactile shadows',
        pov: 'macro to wide',
        composition: 'rule of thirds',
        vibe: 'surreal',
        mood: 'dynamic',
        atmosphere: 'surreal sportscape',
        weather: 'indoor',
        timeOfDay: 'daylight',
        season: 'all seasons',
        windSpeed: 'still',
        visibility: 'clear',
        sense: 'visual',
        colors: 'neon green and clay',
        textures: 'felt and clay',
        materials: 'tennis ball felt and clay',
        temperature: 'warm',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '10 seconds',
        movementSpeed: 'slow to dynamic',
        movementDirection: 'spinning',
        lightIntensity: 'soft',
        lightDirection: 'top-down',
        lightColor: 'editorial',
        povDistance: 'macro to wide',
        povLensType: 'macro to normal',
        compositionBalance: 'dynamic',
        compositionDepth: 'deep',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'spinning',
        emotions: 'focus',
        actions: 'ball cracking and tennis play',
        actionSpeed: 'slow crack to fast spin',
        energyLevel: 'dynamic',
        transition: 'seamless loop',
        details:
          'matte neon-green tennis ball, white seam detail, shell-style lid opening upward, miniature curved clay court, floating net, curved fencing and ambient lights, female tennis player centered in middle third, green felt-lined interior shell, spinning tennis ball flying into right third, macro ball exterior reforming at end',
        additionalDetails:
          'no text, only ambient sound and sharp player grunt on impact, loop resolves with ball closing seamlessly into original macro form same angle and lighting',
        model: 'runway',
      } as Partial<FormData>,
      color: '#00b894',
    },
    {
      name: 'Tesla Showroom',
      icon: '🚗',
      description:
        'Cinematic Tesla-branded crate revealing fully formed Tesla vehicle and sleek showroom assembly',
      template: {
        subject:
          'minimalist Tesla-branded crate with glowing seams magically opening to reveal fully formed Tesla vehicle and instantly assembled sleek Tesla-themed showroom around it',
        style: 'cinematic',
        setting:
          'empty futuristic space transforming into minimalist Tesla showroom',
        cameraMovement:
          'fixed wide angle with subtle zooms on key transformations',
        videoStyle: 'cinematic',
        lighting:
          'controlled high-tech transitioning from dim to bright and clean',
        pov: 'wide shot',
        composition: 'rule of thirds',
        vibe: 'futuristic',
        mood: 'innovative',
        atmosphere: 'clean',
        weather: 'indoor',
        timeOfDay: 'daylight',
        season: 'all seasons',
        windSpeed: 'still',
        visibility: 'clear',
        sense: 'visual',
        colors: 'clean and bright',
        textures: 'smooth',
        materials: 'metal and glass',
        temperature: 'neutral',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '12 seconds',
        movementSpeed: 'smooth and precise',
        movementDirection: 'retracting and rising',
        lightIntensity: 'controlled',
        lightDirection: 'high-tech',
        lightColor: 'bright and clean',
        povDistance: 'wide',
        povLensType: 'wide angle',
        compositionBalance: 'centered',
        compositionDepth: 'medium',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'precise',
        emotions: 'awe',
        actions: 'crate opening and showroom assembly',
        actionSpeed: 'smooth and rapid',
        energyLevel: 'precise',
        transition: 'smooth',
        details:
          'Tesla-branded crate with glowing seams, Tesla vehicle Model 3/Y/Cybertruck, charging station, minimalist display panels, sleek showroom furniture, ambient lighting elements',
        additionalDetails:
          'no text, magic assembly, showroom, innovation, futuristic, clean design, reveal, pristine inviting Tesla showroom with car as centerpiece',
        model: 'runway',
      } as Partial<FormData>,
      color: '#e17055',
    },
    {
      name: 'Cinematic Trailer',
      icon: '🎬',
      description: 'Epic cinematic video with dramatic lighting and movement',
      template: {
        subject: 'epic cinematic scene',
        style: 'cinematic',
        setting: 'urban cityscape',
        cameraMovement: 'dolly in',
        videoStyle: 'cinematic',
        lighting: 'artificial lighting',
        pov: 'medium shot',
        composition: 'rule of thirds',
        vibe: 'dramatic',
        mood: 'intense',
        atmosphere: 'foggy',
        weather: 'cloudy',
        timeOfDay: 'night',
        season: 'autumn',
        windSpeed: 'moderate',
        visibility: 'hazy',
        sense: 'visual',
        colors: 'warm tones',
        textures: 'smooth',
        materials: 'metal',
        temperature: 'cool',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '30 seconds',
        movementSpeed: 'slow',
        movementDirection: 'forward',
        lightIntensity: 'dramatic',
        lightDirection: 'from the side',
        lightColor: 'warm',
        povDistance: 'medium',
        povLensType: 'normal',
        compositionBalance: 'asymmetrical',
        compositionDepth: 'deep',
        atmosphereDensity: 'medium',
        atmosphereMovement: 'gentle',
        emotions: 'excitement',
        actions: 'walking',
        actionSpeed: 'normal speed',
        energyLevel: 'high energy',
        transition: 'fade in',
        details: 'dramatic lighting and shadows',
        additionalDetails: 'cinematic color grading',
        model: 'runway',
      } as Partial<FormData>,
      color: '#7dd8e0',
    },
    {
      name: 'Product Commercial',
      icon: '📱',
      description: 'Professional product showcase with clean aesthetics',
      template: {
        subject: 'premium product showcase',
        style: 'commercial',
        setting: 'indoor studio',
        cameraMovement: 'zoom in',
        videoStyle: 'commercial',
        lighting: 'studio lighting',
        pov: 'close up',
        composition: 'centered',
        vibe: 'modern',
        mood: 'serious',
        atmosphere: 'clear',
        weather: 'calm',
        timeOfDay: 'afternoon',
        season: 'summer',
        windSpeed: 'calm',
        visibility: 'clear',
        sense: 'tactile',
        colors: 'vibrant',
        textures: 'smooth',
        materials: 'glass',
        temperature: 'room temperature',
        humidity: 'dry',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '30 fps',
        videoDuration: '15 seconds',
        movementSpeed: 'slow',
        movementDirection: 'forward',
        lightIntensity: 'bright',
        lightDirection: 'front',
        lightColor: 'white',
        povDistance: 'close',
        povLensType: 'normal',
        compositionBalance: 'symmetrical',
        compositionDepth: 'shallow',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'still',
        emotions: 'excitement',
        actions: 'standing',
        actionSpeed: 'normal speed',
        energyLevel: 'moderate',
        transition: 'cut',
        details: 'clean product presentation',
        additionalDetails: 'professional lighting setup',
        model: 'runway',
      } as Partial<FormData>,
      color: '#6b9ac4',
    },
    {
      name: 'Nature Documentary',
      icon: '🌿',
      description: 'Peaceful nature scenes with organic movement',
      template: {
        subject: 'breathtaking nature landscape',
        style: 'documentary',
        setting: 'mountain landscape',
        cameraMovement: 'pan left',
        videoStyle: 'documentary',
        lighting: 'natural daylight',
        pov: 'wide shot',
        composition: 'leading lines',
        vibe: 'peaceful',
        mood: 'calm',
        atmosphere: 'clear',
        weather: 'sunny',
        timeOfDay: 'golden hour',
        season: 'spring',
        windSpeed: 'light breeze',
        visibility: 'clear',
        sense: 'visual',
        colors: 'earth tones',
        textures: 'smooth',
        materials: 'stone',
        temperature: 'warm',
        humidity: 'moderate',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '24 fps',
        videoDuration: '60 seconds',
        movementSpeed: 'slow',
        movementDirection: 'smooth',
        lightIntensity: 'soft',
        lightDirection: 'from above',
        lightColor: 'warm',
        povDistance: 'long',
        povLensType: 'wide angle',
        compositionBalance: 'organic',
        compositionDepth: 'deep',
        atmosphereDensity: 'thin',
        atmosphereMovement: 'gentle',
        emotions: 'wonder',
        actions: 'walking',
        actionSpeed: 'slow motion',
        energyLevel: 'calm',
        transition: 'cross fade',
        details: 'natural wildlife and vegetation',
        additionalDetails: 'atmospheric nature sounds',
        model: 'runway',
      } as Partial<FormData>,
      color: '#7fb069',
    },
    {
      name: 'Action Sequence',
      icon: '⚡',
      description: 'High-energy action with dynamic camera work',
      template: {
        subject: 'intense action sequence',
        style: 'action',
        setting: 'urban cityscape',
        cameraMovement: 'handheld shake',
        videoStyle: 'action',
        lighting: 'artificial lighting',
        pov: 'point of view',
        composition: 'diagonal',
        vibe: 'energetic',
        mood: 'intense',
        atmosphere: 'stormy',
        weather: 'stormy',
        timeOfDay: 'evening',
        season: 'autumn',
        windSpeed: 'strong',
        visibility: 'hazy',
        sense: 'movement',
        colors: 'vibrant',
        textures: 'rough',
        materials: 'metal',
        temperature: 'cool',
        humidity: 'humid',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '60 fps',
        videoDuration: '20 seconds',
        movementSpeed: 'fast',
        movementDirection: 'jerky',
        lightIntensity: 'intense',
        lightDirection: 'from the side',
        lightColor: 'cool',
        povDistance: 'close',
        povLensType: 'wide angle',
        compositionBalance: 'diagonal',
        compositionDepth: 'shallow',
        atmosphereDensity: 'thick',
        atmosphereMovement: 'turbulent',
        emotions: 'excitement',
        actions: 'running',
        actionSpeed: 'fast motion',
        energyLevel: 'explosive',
        transition: 'whip pan',
        details: 'dynamic movement and action',
        additionalDetails: 'special effects and explosions',
        model: 'runway',
      } as Partial<FormData>,
      color: '#e8a5c4',
    },
    {
      name: 'Artistic Abstract',
      icon: '🎨',
      description: 'Creative abstract visuals with artistic flair',
      template: {
        subject: 'abstract artistic composition',
        style: 'artistic',
        setting: 'abstract space',
        cameraMovement: 'circular motion',
        videoStyle: 'artistic',
        lighting: 'artificial lighting',
        pov: 'wide shot',
        composition: 'circular',
        vibe: 'creative',
        mood: 'whimsical',
        atmosphere: 'misty',
        weather: 'foggy',
        timeOfDay: 'dawn',
        season: 'spring',
        windSpeed: 'gentle',
        visibility: 'misty',
        sense: 'light',
        colors: 'vibrant',
        textures: 'textured',
        materials: 'glass',
        temperature: 'warm',
        humidity: 'humid',
        aspectRatio: '16:9',
        quality: 'high',
        frameRate: '30 fps',
        videoDuration: '45 seconds',
        movementSpeed: 'variable',
        movementDirection: 'circular',
        lightIntensity: 'moody',
        lightDirection: '45-degree',
        lightColor: 'purple',
        povDistance: 'medium',
        povLensType: 'fisheye',
        compositionBalance: 'radial',
        compositionDepth: 'infinite',
        atmosphereDensity: 'wispy',
        atmosphereMovement: 'flowing',
        emotions: 'wonder',
        actions: 'dancing',
        actionSpeed: 'variable speed',
        energyLevel: 'delicate',
        transition: 'morph',
        details: 'abstract shapes and forms',
        additionalDetails: 'creative visual effects',
        model: 'runway',
      } as Partial<FormData>,
      color: '#f4a261',
    },
  ];

  return (
    <div className="preset-templates">
      {/* Decorative top border */}
      <div className="preset-templates__top-border" />

      <h3 className="preset-templates__title">
        <span style={{ fontSize: '24px' }}>🚀</span>
        Quick Start Templates
      </h3>

      <p className="preset-templates__desc">
        Choose a template to quickly set up common video styles, then customize
        as needed.
      </p>

      <div className="preset-templates__grid">
        {templates.map((template, index) => (
          <div
            key={index}
            className="preset-templates__card"
            style={{
              borderColor: 'rgba(255, 255, 255, 0.04)',
              boxShadow: 'none',
            }}
            onMouseEnter={e => {
              e.currentTarget.style.background = 'rgba(255, 255, 255, 0.04)';
              e.currentTarget.style.borderColor = `${template.color}40`;
              e.currentTarget.style.transform = 'translateY(-2px)';
              e.currentTarget.style.boxShadow = `0 8px 25px ${template.color}20`;
            }}
            onMouseLeave={e => {
              e.currentTarget.style.background = 'rgba(255, 255, 255, 0.02)';
              e.currentTarget.style.borderColor = 'rgba(255, 255, 255, 0.04)';
              e.currentTarget.style.transform = 'translateY(0)';
              e.currentTarget.style.boxShadow = 'none';
            }}
            onClick={() => onApplyTemplate(template.template, template.name)}
          >
            {/* Template color accent */}
            <div
              className="preset-templates__card-accent"
              style={{ background: template.color }}
            />

            <div className="preset-templates__card-header">
              <span className="preset-templates__card-icon">
                {template.icon}
              </span>
              <h4 className="preset-templates__card-title">{template.name}</h4>
            </div>

            <p className="preset-templates__card-desc">
              {template.description}
            </p>

            <button
              className="preset-templates__card-btn"
              style={{
                background: `linear-gradient(135deg, ${template.color}20, ${template.color}10)`,
                border: `1px solid ${template.color}40`,
                color: template.color,
              }}
              onMouseEnter={e => {
                e.currentTarget.style.background = `${template.color}30`;
                e.currentTarget.style.borderColor = `${template.color}60`;
              }}
              onMouseLeave={e => {
                e.currentTarget.style.background = `linear-gradient(135deg, ${template.color}20, ${template.color}10)`;
                e.currentTarget.style.borderColor = `${template.color}40`;
              }}
            >
              Apply Template
            </button>
          </div>
        ))}
      </div>

      {/* Bottom decoration */}
      <div className="preset-templates__bottom-bar" />
    </div>
  );
}
